//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cshar_database_proj
{
    using global::System;
    using global::System.Collections.Generic;
    
    public partial class CarsInService
    {
        public int CarsInServiceID { get; set; }
        public int CarID { get; set; }
        public string Comments { get; set; }
        public int CarStatus { get; set; }
        public Nullable<global::System.DateTime> StartServTime { get; set; }
        public Nullable<global::System.DateTime> StopServTime { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual RepairStatus RepairStatus { get; set; }
    }
}
