//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cshar_database_proj
{
    using global::System;
    using global::System.Collections.Generic;
    
    public partial class CarsSold
    {
        public int CarsSoldID { get; set; }
        public int CarID { get; set; }
        public Nullable<global::System.DateTime> SoldTime { get; set; }
    
        public virtual Cars Cars { get; set; }
    }
}
